import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import SessionWrapper from "@/components/SessionWrapper";
import { GlobalContextProvider } from "@/context/GlobalContext";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionWrapper>
      <GlobalContextProvider>
        <html lang="en">
          <body className={`font-sans ${inter.variable} overflow-hidden`}>
            <TRPCReactProvider>{children}</TRPCReactProvider>
          </body>
        </html>
      </GlobalContextProvider>
    </SessionWrapper>
  );
}
