import "@/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "@/trpc/react";
import SessionWrapper from "@/components/SessionWrapper";
import { GlobalContextProvider } from "@/context/GlobalContext";
import { Toaster } from "@/components/ui/toaster";
import { Toaster as ReactHotToaster } from "react-hot-toast";
import { Header } from "@/components/ui/Home/Header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionWrapper>
      <GlobalContextProvider>
        <html lang="en">
          <body className={`font-sans ${inter.variable} overflow-y-auto`}>
            <ReactHotToaster position="top-center" />
            <TRPCReactProvider>
              <div className="flex w-full flex-col overflow-hidden">
                <Header />
                {children}
              </div>
            </TRPCReactProvider>
            <Toaster />
          </body>
        </html>
      </GlobalContextProvider>
    </SessionWrapper>
  );
}
